// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAopS2TtT0pmzeEVl5MljS8QUs9PSBpwo8',
    appId: '1:334894705295:web:2558c7346a9fd4f9d99efa',
    messagingSenderId: '334894705295',
    projectId: 'flutter-chat-app-4a613',
    authDomain: 'flutter-chat-app-4a613.firebaseapp.com',
    storageBucket: 'flutter-chat-app-4a613.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARm_qeljulKnQ600hgseP2rbL5eksEYx4',
    appId: '1:334894705295:android:5942c8db3ba0c5fed99efa',
    messagingSenderId: '334894705295',
    projectId: 'flutter-chat-app-4a613',
    storageBucket: 'flutter-chat-app-4a613.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_3IMiSq6-8h2yo0yRybIj1UqVevsjmY8',
    appId: '1:334894705295:ios:39fb6a1e8bae9d01d99efa',
    messagingSenderId: '334894705295',
    projectId: 'flutter-chat-app-4a613',
    storageBucket: 'flutter-chat-app-4a613.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

}